package sap.ui.model.analytics;

@:native("sap.ui.model.analytics.AnalyticalBinding")

/**
* Tree binding implementation for OData entity sets with aggregate semantics.

Note on the handling of different count modes: The AnalyticalBinding always uses the OData $inlinecount system query option to determine the total count of matching entities. It ignores the default count mode set in the ODataModel instance and the count mode specified in the binding parameters. If the default count mode is None, a warning is added to the log to remind the application that OData requests generated by the AnalyticalBinding will include a $inlinecount. If a count mode has been specified in the binding parameters, an error message will be logged if it is None, because the binding will still add the $inlinecount to OData requests. If a binding count mode is set to Request or Both, a warning will be logged to remind the application that the OData requests generated by the AnalyticalBinding will include a $inlinecount.
*/
extern class AnalyticalBinding extends sap.ui.model.TreeBinding
{

	/**
	* Creates a new subclass of class sap.ui.model.analytics.AnalyticalBinding with name <code>sClassName</code> and enriches it with the information contained in <code>oClassInfo</code>.

<code>oClassInfo</code> might contain the same kind of information as described in {@link sap.ui.model.TreeBinding.extend}.
	* @param	sClassName Name of the class being created
	* @param	oClassInfo Object literal with information about the class
	* @param	FNMetaImpl Constructor function for the metadata object; if not given, it defaults to <code>sap.ui.core.ElementMetadata</code>
	* @return	Created class / constructor function
	*/
	public static function extend( sClassName:String, ?oClassInfo:Dynamic, ?FNMetaImpl:()->Void):()->Void;
	@:overload( function(aFilter:Array<sap.ui.model.Filter>, ?sFilterType:sap.ui.model.FilterType):sap.ui.model.analytics.AnalyticalBinding{ })

	/**
	* Sets filters for matching only a subset of the entities in the bound OData entity set.

Invoking this function resets the state of the binding. Subsequent data requests such as calls to getNodeContexts() will need to trigger OData requests in order to fetch the data that are in line with these filters.
	* @param	aFilter an Array of sap.ui.model.Filter objects or a single Filter instance.
	* @param	sFilterType Type of the filter which should be adjusted.
	* @return	returns <code>this</code> to facilitate method chaining
	*/
	public function filter( aFilter:sap.ui.model.Filter, ?sFilterType:sap.ui.model.FilterType):sap.ui.model.analytics.AnalyticalBinding;

	/**
	* Gets the analytical information for a column with a given name.
	* @param	sColumnName the column name.
	* @return	analytical information for the column; see {@link #updateAnalyticalInfo} for an explanation of the object structure
	*/
	public function getAnalyticalInfoForColumn( sColumnName:String):Dynamic;

	/**
	* Gets analytical metadata for the bound OData entity set.
	* @return	analytical metadata for the bound OData entity set
	*/
	public function getAnalyticalQueryResult( ):sap.ui.model.analytics.odata4analytics.QueryResult;

	/**
	* Gets details about the dimension properties included in the bound OData entity set.
	* @return	details for every dimension property addressed by its name. The details object provides these properties: name of the dimension, keyPropertyName for the name of the property holding the dimension key, textPropertyName for the name of the property holding the text for the dimension, aAttributeName listing all properties holding dimension attributes, grouped as indicator whether or not this dimension is currently grouped, and analyticalInfo, which contains the binding information for this dimension passed from the AnalyticalBinding's consumer via call to function updateAnalyticalInfo.
	*/
	public function getDimensionDetails( ):Dynamic;

	/**
	* Get a download URL with the specified format considering the sort/filter/custom parameters.

The download URL also takes into account the selected dimensions and measures, depending on the given column definitions of the AnalyticalTable. This is based on the visible/inResult flags of the columns, as well as integrity dependencies, e.g. for mandatory Unit properties.
	* @param	sFormat Value for the $format Parameter
	* @return	URL which can be used for downloading
	*/
	public function getDownloadUrl( sFormat:String):String;

	/**
	* Gets the names of the filterable properties in the bound OData entity set.
	* @return	names of properties that can be filtered.
	*/
	public function getFilterablePropertyNames( ):Array<Dynamic>;

	/**
	* Gets a printable name for a group.

The printable name follows the pattern is <code>&lt;label&gt;:&lt;key-value&gt;[-&lt;text-value&gt;]</code>, where <code>label</code> is the label of the dimension property used at the aggregation level for the group, <code>key-value</code> is the key value of that dimension for the group, and <code>text-value</code> is the value of the associated text property, if it is also used in the binding.

Whenever a formatter function has been defined for a column displaying the key or text of this dimension, the return value of this function is applied for the group name instead of the respective key or text value.
	* @param	oContext the parent context identifying the requested group.
	* @param	iLevel the level number of oContext (because the context might occur at multiple levels)
	* @return	a printable name for the group.
	*/
	public function getGroupName( oContext:sap.ui.model.Context, iLevel:Int):String;

	/**
	* Gets the total number of contexts contained in a group, if known.

For a given group, be aware that the group size might vary over time. In principle, this can happen if the bound set of OData entities includes measure properties with amount or quantity values. The AnalyticalBinding recognizes situations where the OData service returns multiple entries for a single group entry due to the fact that a measure property cannot be aggregated properly, because an amount exists in multiple currencies or a quantity exists in multiple units. In such situations, the AnalyticalBinding substitutes these entries by a single representative, and the group size gets reduced by the count of duplicate entries. Finally, since the Binding does not always fetch all children of a group at once, but only a page with a certain range, such size changes might happen after every page access.
	* @param	oContext the parent context identifying the requested group of child contexts.
	* @param	iLevel the level number of oContext (because the context might occur at multiple levels)
	* @return	The currently known group size, or -1, if not yet determined
	*/
	public function getGroupSize( oContext:sap.ui.model.Context, iLevel:Int):Int;

	/**
	* Gets details about the measure properties included in the bound OData entity set.
	* @return	details for every measure property addressed by its name. The details object provides these properties: name of the measure, rawValuePropertyName for the name of the property holding the raw value, unitPropertyName for the name of the property holding the related value unit or currency, if any, and analyticalInfo, which contains the binding information for this measure passed from the AnalyticalBinding's consumer via call to function updateAnalyticalInfo.
	*/
	public function getMeasureDetails( ):Dynamic;

	/**
	* Returns a metadata object for class sap.ui.model.analytics.AnalyticalBinding.
	* @return	Metadata object describing this class
	*/
	public static function getMetadata( ):sap.ui.base.Metadata;

	/**
	* Gets child contexts for a specified parent context.

Contexts are returned in a stable order imposed by the dimension property that defines this aggregation level beneath the parent context: Either a sort order has been specified for this property, or the entries are returned in ascending order of the values of this dimension property by default.

If any of the requested data is missing, an OData request will be triggered to load it.
	* @param	mParameters specifying the aggregation level for which contexts shall be fetched. Supported parameters are: <ul> <li>oContext: parent context identifying the requested group of child contexts</li> <li>level: level number for oContext, because it might occur at multiple levels; context with group ID <code>"/"</code> has level 0</li> <li>numberOfExpandedLevels: number of child levels that shall be fetched automatically</li> <li>startIndex: index of first child entry to return from the parent context (zero-based)</li> <li>length: number of entries to return; counting begins at the given start index</li> <li>threshold: number of additional entries that shall be locally available in the binding for subsequent accesses to child entries of the given parent context. </li> </ul>
	* @return	Array containing the requested contexts of class sap.ui.model.Context, limited by the number of entries contained in the entity set at that aggregation level. The array will contain less than the requested number of contexts, if some are not locally available and an OData request is pending to fetch them. In this case, if the parameter numberOfExpandedLevels > 0, the array will be completely empty.
	*/
	public function getNodeContexts( mParameters:Dynamic):Array<Dynamic>;

	/**
	* Gets the metadata of a property with a given name.
	* @param	sPropertyName The property name.
	* @return	OData metadata of this property or null if it does not exist.
	*/
	public function getProperty( sPropertyName:String):Dynamic;

	/**
	* Gets the label of a property with a given name.
	* @param	sPropertyName The property name.
	* @return	The heading maintained for this property or null if it does not exist.
	*/
	public function getPropertyHeading( sPropertyName:String):String;

	/**
	* Gets the label of a property with a given name.
	* @param	sPropertyName The property name.
	* @return	The label maintained for this property or null if it does not exist.
	*/
	public function getPropertyLabel( sPropertyName:String):String;

	/**
	* Gets the quick info of a property with a given name.
	* @param	sPropertyName The property name.
	* @return	The quick info maintained for this property or null if it does not exist.
	*/
	public function getPropertyQuickInfo( sPropertyName:String):String;

	/**
	* Gets the context for the root aggregation level representing the grand total for all bound measure properties.

The context is assigned to parent group ID <code>null</code>. If the binding is configured not to provide a grand total, this context is empty. If data for this context is not locally available yet, an OData request will be triggered to load it.

This function must be called whenever the bound set of OData entities changes, e.g., by changing selected dimensions, modifying filter conditions, etc.
	* @param	mParameters specifying how the top-most aggregation level shall be fetched. Supported parameters are: <ul> <li>numberOfExpandedLevels: number of child levels that shall be fetched automatically</li> <li>startIndex: index of first entry to return from parent group ID <code>"/"</code> (zero-based)</li> <li>length: number of entries to return at and after the given start index</li> <li>threshold: number of additional entries that shall be locally available in the binding for subsequent accesses to contexts of parent group ID <code>"/"</code> or below, if auto-expanding is selected</li> </ul>
	* @return	Array with a single object of class sap.ui.model.Context for the root context, or an empty array if an OData request is pending to fetch requested contexts that are not yet locally available.
	*/
	public function getRootContexts( mParameters:Dynamic):Array<Dynamic>;

	/**
	* Gets the names of the sortable properties in the bound OData entity set.
	* @return	names of properties that can be used for sorting the result entities.
	*/
	public function getSortablePropertyNames( ):Array<Dynamic>;

	/**
	* Gets the total number of entities in the bound OData entity set.

Counting takes place at the lowest aggregation level defined by the possible value combinations for the complete set of dimension properties included in the bound entity set. This means that intermediate aggregate entities with sub-totals at higher aggregation levels are not counted.
	* @return	the total number of addressed entities in the OData entity set
	*/
	public function getTotalSize( ):Int;

	/**
	* Determines if the binding has the entries of a given aggregation level locally available.

If so, no further OData request is required to fetch any of them.
	* @param	oContext the parent context identifying the aggregation level.
	* @param	iLevel the level number of oContext (because the context might occur at multiple levels).
	* @return	property of sap.ui.model.analytics.AnalyticalBinding.ContextsAvailabilityStatus, indicating whether all, some, or none of the entries are locally available.
	*/
	public function hasAvailableNodeContexts( oContext:sap.ui.model.Context, iLevel:Int):Bool;

	/**
	* Determines if the contexts in a specified group have further children. If so, any of these group contexts can be a parent context of a nested sub-group in a subsequent aggregation level.
	* @param	oContext the parent context identifying the requested group of child contexts.
	* @param	mParameters The only supported parameter is level as the level number of oContext (because the context might occur at multiple levels)
	* @return	true if and only if the contexts in the specified group have further children.
	*/
	public function hasChildren( oContext:sap.ui.model.Context, mParameters:Dynamic):Bool;

	/**
	* Determines if any of the properties included in the bound OData entity set is a measure property.
	* @return	true if and only one or more properties are measure properties.
	*/
	public function hasMeasures( ):Bool;

	/**
	* Determines if a given name refers to a measure property
	* @param	sPropertyName The property name.
	* @return	true if and only if the bound OData entity set includes a measure property with this name.
	*/
	public function isMeasure( sPropertyName:String):Bool;

	/**
	* Loads child contexts of multiple groups.
	* @param	mGroupIdRanges specifies index ranges of child contexts to be loaded for multiple groups identified by their ID. A group index range is given by an object consisting of startIndex, length, threshold. For every group ID, the map holds an array of such range objects.
	* @return	Void
	*/
	public function loadGroups( mGroupIdRanges:Dynamic):Void;

	/**
	* Determines if the binding has been configured to provide a grand total for the selected measure properties.
	* @return	true if and only if the binding provides a context for the grand totals of all selected measure properties.
	*/
	public function providesGrandTotal( ):Bool;

	/**
	* Refreshes the binding, check whether the model data has been changed and fire change event if this is the case. For service side models this should refetch the data from the service. To update a control, even if no data has been changed, e.g. to reset a control after failed validation, please use the parameter bForceUpdate.
	* @param	bForceUpdate Update the bound control even if no data has been changed
	* @return	Void
	*/
	public function refresh( ?bForceUpdate:Bool):Void;
	@:overload( function(aSorter:sap.ui.model.Sorter):sap.ui.model.analytics.AnalyticalBinding{ })

	/**
	* Sets sorters for retrieving the entities in the bound OData entity set in a specific order.

Invoking this function resets the state of the binding. Subsequent data requests such as calls to getNodeContexts() will need to trigger OData requests in order to fetch the data that are in line with these sorters.
	* @param	aSorter a sorter object or an array of sorter objects which define the sort order.
	* @return	returns <code>this</code> to facilitate method chaining.
	*/
	public function sort( aSorter:Array<Dynamic>):sap.ui.model.analytics.AnalyticalBinding;
}

